# Generated by Django 5.1.6 on 2025-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('role', models.IntegerField(choices=[(1, 'STUDENT'), (2, 'TEACHER'), (3, 'PARENT')])),
            ],
        ),
    ]
