# Generated by Django 5.1.6 on 2025-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_role_user_birth_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.IntegerField(choices=[('Student', 'STUDENT'), ('Teacher', 'TEACHER'), ('Parent', 'PARENT')]),
        ),
    ]
