# Generated by Django 5.1.6 on 2025-03-10 18:39

import django.db.models.deletion
import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_role_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_hex', models.CharField(max_length=4)),
                ('start_year', models.IntegerField()),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_guardian', to='main.parent')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school_class')),
                ('second_guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_guardian', to='main.parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name=main.enums.TeacherSubject)),
                ('eployment_year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='School_class_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_role', models.CharField(verbose_name=main.enums.TeacherRole)),
                ('subject', models.CharField(verbose_name=main.enums.TeacherSubject)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school_class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
