# Generated by Django 5.1.6 on 2025-03-15 11:31

import datetime
import django.db.models.deletion
import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_school_class_parent_student_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('begin_time', models.DateField(default=datetime.date(2025, 3, 15))),
                ('end_time', models.DateField()),
                ('context', models.CharField(max_length=325)),
                ('event_position', models.CharField()),
                ('event_status', models.CharField(verbose_name=main.enums.EventStatus)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('begin_time', models.DateField(default=datetime.date(2025, 3, 15))),
                ('end_time', models.DateField()),
                ('context', models.CharField(max_length=325)),
                ('status', models.CharField(verbose_name=main.enums.TaskStatus)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.CharField(verbose_name=main.enums.UserRole),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.school_class'),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.school_class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_guardian', to='main.parent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.role'),
        ),
    ]
