# Generated by Django 5.1.6 on 2025-03-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_added_task_and_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin_time',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 11, 33, 3, 316887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 11, 33, 3, 334880, tzinfo=datetime.timezone.utc)),
        ),
    ]
