# Generated by Django 5.1.6 on 2025-03-15 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_added_task_and_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
