# Generated by Django 5.1.6 on 2025-03-18 18:09

from django.db import migrations


class Migration(migrations.Migration):
   
    dependencies = [
        ('main', '0007_added_task_and_event'),
    ]

    def save_roles(apps, schema_editor):
        roles = [{
            "key": "teacher",
            "title": "Teachers role",
            "description": "Role for teachers" 
            }, {
            "key": "student",
            "title": "Students role",
            "description": "Role for students" 
            }, {
            "key": "parent",
            "title": "Parents role",
            "description": "Role for parents" 
            }]
            
        Role = apps.get_model('main', 'Role')
        
        for item in roles:
            role = Role(key = item["key"], title=item["title"], description=item["description"])
            role.save()

    operations = [
        migrations.RunPython(save_roles)
    ]
