# Generated by Django 5.1.6 on 2025-03-19 17:06

import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(editable=False, verbose_name=main.enums.EventStatus.choices),
        ),
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.CharField(editable=False, verbose_name=main.enums.UserRole.choices),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='subject',
            field=models.CharField(editable=False, verbose_name=main.enums.TeacherSubject.choices),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='teacher_role',
            field=models.CharField(editable=False, verbose_name=main.enums.TeacherRole.choices),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(editable=False, verbose_name=main.enums.TaskStatus.choices),
        ),
    ]
