# Generated by Django 5.1.6 on 2025-03-19 18:13

import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_event_status_alter_role_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=main.enums.EventStatus.choices, editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.CharField(choices=main.enums.UserRole.choices, editable=False),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='subject',
            field=models.CharField(choices=main.enums.TeacherSubject.choices, editable=False),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='teacher_role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Headmaster', 'Headmaster')], editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=main.enums.TaskStatus.choices, editable=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=main.enums.TeacherSubject.choices),
        ),
    ]
