# Generated by Django 5.1.6 on 2025-03-19 18:48

import django.db.models.deletion
import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_school_alter_event_event_status_alter_role_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_position',
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_adress',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
        migrations.AlterField(
            model_name='school_class',
            name='prefix_hex',
            field=models.CharField(help_text='d090->А, d091->Б, d092->В, d093->Г', max_length=4),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='subject',
            field=models.CharField(choices=main.enums.TeacherSubject.choices),
        ),
        migrations.AlterField(
            model_name='school_class_teacher',
            name='teacher_role',
            field=models.CharField(choices=main.enums.TeacherRole.choices),
        ),
    ]
