# Generated by Django 5.1.7 on 2025-03-29 09:37

import django.db.models.deletion
import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_eployment_year_teacher_employment_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='customer',
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_adress',
            field=models.CharField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='school_class',
            name='prefix_hex',
            field=models.CharField(choices=[('А', 'A'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=main.enums.TaskStatus.choices),
        ),
    ]
