# Generated by Django 5.1.7 on 2025-04-22 18:27

import main.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_task_customer_event_creator_task_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url_adress',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_adress',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=main.enums.EventStatus.choices),
        ),
    ]
